version: '3'
services:
  forum:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: alura/forum
    ports:
      - '8080:8080'
    environment:
      - PROFILE=prod
    depends_on: 
      - db
    links:
      - db
      
  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: forum
      MYSQL_PASSWORD: 15491549
      MYSQL_ROOT_PASSWORD: 15491549
    volumes:
      - db-API:/var/lib/mysql
volumes:
  db-API:
